### ISSUE TITLE
DOTweenEditorPreview.isPreviewing does not exist

### ISSUE THREAD

**Issue by O-S-K** [brunomikoski/Animation-Sequencer#67] opened 2023-05-21 21:27 UTC
The new version of DOTween, DOTweenEditorPreview.isPreviewing is not declared so it can't be referenced, do you have any fix?

**Comment by brunomikoski** [comment] 2023-06-01 12:30
I just tested with the latest DOTween (v1.2.705)and everything is working as intended, can you confirm what version you are using?

**Comment by O-S-K** [comment] 2023-06-03 17:22
oh it's strange that my version doesn't have DOTweenEditorPreview.isPreviewing

**Comment by O-S-K** [comment] 2023-06-03 17:30
i used the old version of DOTween, i updated to the latest version and it worked, thank you for your contribution

**Comment by O-S-K** [comment] 2023-06-03 17:32
What's better if you already have some Animation Sequencer demos

**Comment by brunomikoski** [comment] 2023-06-05 14:09
> What's better if you already have some Animation Sequencer demos

Yeah, I have plans to add a few examples, but I'm currently doing a big refactoring on the system. I update this thread when I have something! 

In the meantime, I will close this issue since was invalid okay?

**Closed as completed by brunomikoski** 2023-06-05 14:09 UTC
Labels: invalid
